/* tslint:disable */
/* eslint-disable */
/**
 * Flavorite - OpenAPI 3.0
 * This is a Flavorite Server based on the OpenAPI 3.0 specification. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FavoriteFood
 */
export interface FavoriteFood {
    /**
     * 
     * @type {number}
     * @memberof FavoriteFood
     */
    order: number;
    /**
     * 
     * @type {string}
     * @memberof FavoriteFood
     */
    name: string;
}

export function FavoriteFoodFromJSON(json: any): FavoriteFood {
    return FavoriteFoodFromJSONTyped(json, false);
}

export function FavoriteFoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoriteFood {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': json['order'],
        'name': json['name'],
    };
}

export function FavoriteFoodToJSON(value?: FavoriteFood | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
        'name': value.name,
    };
}


