/* tslint:disable */
/* eslint-disable */
/**
 * Flavorite - OpenAPI 3.0
 * This is a Flavorite Server based on the OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Restaurant,
    RestaurantFromJSON,
    RestaurantFromJSONTyped,
    RestaurantToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListRestaurants
 */
export interface ListRestaurants {
    /**
     * 
     * @type {Array<Restaurant>}
     * @memberof ListRestaurants
     */
    restaurants: Array<Restaurant>;
}

export function ListRestaurantsFromJSON(json: any): ListRestaurants {
    return ListRestaurantsFromJSONTyped(json, false);
}

export function ListRestaurantsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRestaurants {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'restaurants': ((json['restaurants'] as Array<any>).map(RestaurantFromJSON)),
    };
}

export function ListRestaurantsToJSON(value?: ListRestaurants | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'restaurants': ((value.restaurants as Array<any>).map(RestaurantToJSON)),
    };
}


