/* tslint:disable */
/* eslint-disable */
/**
 * Flavorite - OpenAPI 3.0
 * This is a Flavorite Server based on the OpenAPI 3.0 specification. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FavoriteFood,
    FavoriteFoodFromJSON,
    FavoriteFoodFromJSONTyped,
    FavoriteFoodToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListFavoriteFoods
 */
export interface ListFavoriteFoods {
    /**
     * 
     * @type {Array<FavoriteFood>}
     * @memberof ListFavoriteFoods
     */
    favoriteFoods: Array<FavoriteFood>;
}

export function ListFavoriteFoodsFromJSON(json: any): ListFavoriteFoods {
    return ListFavoriteFoodsFromJSONTyped(json, false);
}

export function ListFavoriteFoodsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFavoriteFoods {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'favoriteFoods': ((json['favoriteFoods'] as Array<any>).map(FavoriteFoodFromJSON)),
    };
}

export function ListFavoriteFoodsToJSON(value?: ListFavoriteFoods | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'favoriteFoods': ((value.favoriteFoods as Array<any>).map(FavoriteFoodToJSON)),
    };
}


