/* tslint:disable */
/* eslint-disable */
/**
 * Flavorite - OpenAPI 3.0
 * This is a Flavorite Server based on the OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListFriends
 */
export interface ListFriends {
    /**
     * 
     * @type {Array<User>}
     * @memberof ListFriends
     */
    friends: Array<User>;
}

export function ListFriendsFromJSON(json: any): ListFriends {
    return ListFriendsFromJSONTyped(json, false);
}

export function ListFriendsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFriends {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'friends': ((json['friends'] as Array<any>).map(UserFromJSON)),
    };
}

export function ListFriendsToJSON(value?: ListFriends | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'friends': ((value.friends as Array<any>).map(UserToJSON)),
    };
}


