/* tslint:disable */
/* eslint-disable */
/**
 * Flavorite - OpenAPI 3.0
 * This is a Flavorite Server based on the OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface LoginUser
 */
export interface LoginUser {
  /**
   *
   * @type {string}
   * @memberof LoginUser
   */
  usernameOrEmail: string
  /**
   *
   * @type {string}
   * @memberof LoginUser
   */
  password: string
}

export function LoginUserFromJSON(json: any): LoginUser {
  return LoginUserFromJSONTyped(json, false)
}

export function LoginUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUser {
  if (json === undefined || json === null) {
    return json
  }
  return {
    usernameOrEmail: json['usernameOrEmail'],
    password: json['password'],
  }
}

export function LoginUserToJSON(value?: LoginUser | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    usernameOrEmail: value.usernameOrEmail,
    password: value.password,
  }
}
