/* tslint:disable */
/* eslint-disable */
/**
 * Flavorite - OpenAPI 3.0
 * This is a Flavorite Server based on the OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginPayload
 */
export interface LoginPayload {
    /**
     * 
     * @type {string}
     * @memberof LoginPayload
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof LoginPayload
     */
    username: string;
}

export function LoginPayloadFromJSON(json: any): LoginPayload {
    return LoginPayloadFromJSONTyped(json, false);
}

export function LoginPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'username': json['username'],
    };
}

export function LoginPayloadToJSON(value?: LoginPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'username': value.username,
    };
}


