/* tslint:disable */
/* eslint-disable */
/**
 * Flavorite - OpenAPI 3.0
 * This is a Flavorite Server based on the OpenAPI 3.0 specification. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    restaurantId: number;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    photoUrl?: string;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'restaurantId': json['restaurantId'],
        'rating': json['rating'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'photoUrl': !exists(json, 'photoUrl') ? undefined : json['photoUrl'],
    };
}

export function ReviewToJSON(value?: Review | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'restaurantId': value.restaurantId,
        'rating': value.rating,
        'content': value.content,
        'photoUrl': value.photoUrl,
    };
}


