/* tslint:disable */
/* eslint-disable */
/**
 * Flavorite - OpenAPI 3.0
 * This is a Flavorite Server based on the OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateReview
 */
export interface UpdateReview {
    /**
     * 
     * @type {number}
     * @memberof UpdateReview
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateReview
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateReview
     */
    photoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateReview
     */
    favoriteFood?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateReview
     */
    starred?: boolean;
}

export function UpdateReviewFromJSON(json: any): UpdateReview {
    return UpdateReviewFromJSONTyped(json, false);
}

export function UpdateReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReview {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'photoUrl': !exists(json, 'photoUrl') ? undefined : json['photoUrl'],
        'favoriteFood': !exists(json, 'favoriteFood') ? undefined : json['favoriteFood'],
        'starred': !exists(json, 'starred') ? undefined : json['starred'],
    };
}

export function UpdateReviewToJSON(value?: UpdateReview | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rating': value.rating,
        'content': value.content,
        'photoUrl': value.photoUrl,
        'favoriteFood': value.favoriteFood,
        'starred': value.starred,
    };
}


