/* tslint:disable */
/* eslint-disable */
/**
 * Flavorite - OpenAPI 3.0
 * This is a Flavorite Server based on the OpenAPI 3.0 specification. 
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FavoriteFood,
    FavoriteFoodFromJSON,
    FavoriteFoodFromJSONTyped,
    FavoriteFoodToJSON,
} from './';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: string;
    /**
     * 
     * @type {Array<FavoriteFood>}
     * @memberof User
     */
    favoriteFoods?: Array<FavoriteFood>;
    /**
     * 
     * @type {Array<User>}
     * @memberof User
     */
    friends?: Array<User>;
    /**
     * User Status
     * @type {number}
     * @memberof User
     */
    userStatus?: number;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'favoriteFoods': !exists(json, 'favoriteFoods') ? undefined : ((json['favoriteFoods'] as Array<any>).map(FavoriteFoodFromJSON)),
        'friends': !exists(json, 'friends') ? undefined : ((json['friends'] as Array<any>).map(UserFromJSON)),
        'userStatus': !exists(json, 'userStatus') ? undefined : json['userStatus'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'password': value.password,
        'favoriteFoods': value.favoriteFoods === undefined ? undefined : ((value.favoriteFoods as Array<any>).map(FavoriteFoodToJSON)),
        'friends': value.friends === undefined ? undefined : ((value.friends as Array<any>).map(UserToJSON)),
        'userStatus': value.userStatus,
    };
}


